export const ATTENDANCE_THRESHOLD = 75;
export const FIRST_NAMES = [
  "Alex",
  "Jordan",
  "Casey",
  "Morgan",
  "Taylor",
  "Riley",
  "Avery",
  "Quinn",
  "Drew",
  "Dakota",
  "Blake",
  "Jamie",
  "Reese",
  "Parker",
  "Sydney",
  "Cameron",
  "Charlie",
  "Bailey",
  "Elliott",
  "Finley",
];

export const LAST_NAMES = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Sanchez",
  "Chen",
  "Wang",
  "Kim",
  "Patel",
  "Shah",
  "Lee",
  "Wong",
];
export const API_URL = "https://jsonplaceholder.typicode.com/users";
export const FILTER_OPTIONS = ["All", "Present", "Absent"];
